---
title: "EURO 2020 bet strategy: quarter of finals"
author: "Leonardo Egidi - DEAMS, University of Trieste, Italy. Mail: legidi@units.it"
date: "2 July 2021"
output:
  pdf_document:
    highlight: tango
    keep_tex: yes
    toc: yes
  html_document:
    df_print: paged
    toc: yes
  include: null
  ioslides_presentation:
    highlight: tango
  prettydoc::html_pretty:
    css: style.css
    theme: leonids
    toc: yes
  beamer_presentation:
    highlight: tango
  slide_level: 2
  slidy_presentation:
    fig.height: 3
    fig.width: 4
    highlight: tango
graphics: yes
header-includes:
- \usepackage{color}
- \usepackage{bm}
institute: University of Trieste
fontsize: 10pt
---
```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.align = 'center', warning=FALSE, message=FALSE, fig.asp=0.625, fig.height =10, fig.width = 8, out.width='750px', dpi=200, 
  dev='png', global.par = TRUE, dev.args=list(pointsize=10), fig.path = 'figs/')
library(MASS)
```
```{r setup, include=FALSE}
library(knitr)
local({
  hook_plot = knit_hooks$get('plot')
  knit_hooks$set(plot = function(x, options) {
    paste0('\n\n----\n\n', hook_plot(x, options))
  })
})
```

**Totale**: 130 euro

*1X2*: 100 euro

*Risultati secchi*: 30 euro


Criterio del principio atteso per le puntate + criterio di Kelly per stabilire quanto puntare su ciascuna partita.


```{r puntate, echo=FALSE}
# Svizzera-Spagna
quote1 <- c(5.75, 3.8, 1.61)
prob1 <- c(0.351,0.252,0.397)
# Belgio-Italia
quote2 <- c(3.3, 3, 2.37)
prob2 <- c(0.544,0.262,0.195)
# Rep.Ceca-Danimarca
quote3 <- c(3.8, 3.2, 2.1)
prob3 <- c(0.260,0.277,0.463)
# Ucraina-Inghilterra
quote4 <- c(8.5, 4.5, 1.4)
prob4 <- c(0.187,0.254, 0.559)

quote <- rbind(quote1, quote2, quote3, quote4)
prob <- rbind(prob1, prob2, prob3, prob4)




prob_bk <- function(quote_input){
  bk <- c()
  for (i in 1:3)
      bk[i] <- (1/quote_input[i])/(sum(1/(quote_input)))
  return(bk)
}

#prob_bk(quote)

guadagno_atteso <- prob/prob_bk(quote) -1


#tot_euro <- c(130*prob[1,1], 130*prob[2,1], 0, 130*sum(prob[4,1]+prob[4,2]))
tot_euro <- 100
tab<-round(quote*prob,2)
rownames(tab)<- c("Svi-Spa", "Bel-Ita", "Cec-Dan", "Ucr-Ing")
colnames(tab) <- c("1", "X", "2")
puntate <- c( (2.02+0.96-(1-prob[1,1]-prob[1,2]))/2.2, 
              (1.8-(1-prob[2,1]))/quote[2,1],
              0, (1.59+1.14-(1-prob[4,1]-prob[4,2]))/2.75 )*tot_euro
puntate <- round(puntate*tot_euro/sum(puntate))

atteso <- c(puntate[1] *2.2, puntate[2]*quote[2,1], 0, puntate[4]*2.75)
atteso <- as.numeric(as.vector(atteso))
puntate_secchi <- c("5e (1-1)", "10e (0-0, 0-1)", "5e (0-1)", "10e (0-1)")
atteso_secchi <- c("40", "35,35", "32.5", "60" )
rule <- c("1X", "1", "", "1X")
tab<-cbind(tab, rule, puntate, atteso, puntate_secchi, atteso_secchi)
knitr::kable(tab)
```